version: '3.9'
services:
  db:
    image: mysql:8
    restart: always
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: ${NAME_DB}
      MYSQL_USER: ${USER_DB}
      MYSQL_ROOT_PASSWORD: ${PASSWORD_DB}
      MYSQL_PASSWORD: ${PASSWORD_DB}
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: